services:
  - type: web
    name: ai-codex-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: |
      npm install
      npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
